
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: marina
  password: 123
  host: localhost
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: books_db_production

test:
  <<: *default
  database: books_db_production

production:
  <<: *default
  database: psql_db_production