
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: books_db_development

test:
  <<: *default
  database: books_db_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>